[package]
name = "bbqueue"
version = "0.4.3"
description = "A SPSC, lockless, no_std, thread safe, queue, based on BipBuffers"
repository = "https://github.com/jamesmunns/bbqueue"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"
readme = "../README.md"

categories = [
    "embedded",
    "no-std",
    "memory-management",
]
license = "MIT OR Apache-2.0"

[dependencies]
generic-array = "0.13"
cortex-m = { version = "0.6.0", optional = true }

[features]
default = ["atomic"]
thumbv6 = ["cortex-m"]
atomic = []

# TODO: This doesn't really do anything anymore
std = []


[package.metadata.docs.rs]
all-features = true
