on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Integration Tests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - build: ""
          - build: "--release"

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test ${{ matrix.build }} --features=short-potato --manifest-path bbqtest/Cargo.toml -- --nocapture
