on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: TSAN Integration Test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - build: ""
          - build: "--release"

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rust-src

      - run: cargo test ${{ matrix.build }} --features=short-potato --manifest-path bbqtest/Cargo.toml -Zbuild-std --target x86_64-unknown-linux-gnu -- --nocapture
        env:
          RUSTFLAGS: "-Z sanitizer=thread"
          RUST_TEST_THREADS: 1
          TSAN_OPTIONS: "suppressions=${{ github.workspace }}/tsan-blacklist.txt"
